import { Ticket, Technician, KnowledgeArticle, CannedResponse } from './types';

export const TECHNICIANS: Technician[] = [
  {
    id: 'tech-1',
    name: 'Lucas Morais',
    email: 'lucas.morais@empresa.com.br',
    role: 'Analista de Infraestrutura N2',
    initials: 'LM',
    department: 'TI & Infraestrutura',
    specialty: 'Redes, Servidores e VPN',
  },
  {
    id: 'tech-2',
    name: 'Mariana Siqueira',
    email: 'mariana.siqueira@empresa.com.br',
    role: 'Técnica de Suporte N1',
    initials: 'MS',
    department: 'TI & Infraestrutura',
    specialty: 'Hardware, Windows e Periféricos',
  },
  {
    id: 'tech-3',
    name: 'Rodrigo Valente',
    email: 'rodrigo.valente@empresa.com.br',
    role: 'Analista de Sistemas & ERP',
    initials: 'RV',
    department: 'Sistemas Corporativos',
    specialty: 'Protheus, Relatórios e Integrações',
  },
  {
    id: 'tech-4',
    name: 'Beatriz Albuquerque',
    email: 'beatriz.albuquerque@empresa.com.br',
    role: 'Analista de Segurança & Acessos',
    initials: 'BA',
    department: 'Segurança da Informação',
    specialty: 'Active Directory, Permissões e MFA',
  },
];

export const DEPARTMENTS = [
  'TI & Infraestrutura',
  'Sistemas Corporativos',
  'Recursos Humanos',
  'Financeiro & Fiscal',
  'Operações & Logística',
  'Facilities & Predial',
  'Comercial & Vendas',
];

export const CATEGORIES_CONFIG: Record<string, string[]> = {
  'Hardware & Periféricos': [
    'Notebook não liga',
    'Monitor com falha/piscando',
    'Teclado ou Mouse danificado',
    'Dock station / Hub USB',
    'Impressora / Falha de toner',
    'Substituição preventiva',
  ],
  'Redes & Conectividade': [
    'VPN corporativa inacessível',
    'Queda de sinal Wi-Fi no setor',
    'Ponto de rede sem internet',
    'Lentidão extrema na navegação',
  ],
  'Acessos & Credenciais': [
    'Redefinição de senha de rede',
    'Desbloqueio de usuário no domínio',
    'Permissão para pasta na rede',
    'Criação de e-mail departamental',
    'Problema com Autenticação MFA',
  ],
  'Sistemas & Softwares': [
    'Erro de lançamento no ERP',
    'Licença do Microsoft 365 expirada',
    'Travamento de software específico',
    'Atualização de sistema operacional',
    'Instalação de software homologado',
  ],
  'Facilities & Manutenção': [
    'Ar condicionado desarmando',
    'Iluminação com lâmpada queimada',
    'Tomada sem energia elétrica',
    'Reparo em mobiliário ou gaveteiro',
  ],
  'RH & Pessoal': [
    'Dúvida de ponto eletrônico',
    'Solicitação de segundo crachá',
    'Alteração de dados cadastrais',
  ],
};

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'tick-101',
    protocol: 'CH-2026-0842',
    title: 'VPN não conecta após atualização do Windows 11',
    description: 'Após reiniciar o notebook pela manhã com a atualização obrigatória, o cliente FortiClient apresenta erro "Não foi possível estabelecer túnel seguro (código 98)". Trabalho em regime híbrido e preciso acessar os arquivos do servidor de arquivos hoje.',
    category: 'Redes & Conectividade',
    subcategory: 'VPN corporativa inacessível',
    department: 'TI & Infraestrutura',
    requester: {
      name: 'Camila Fernandes',
      email: 'camila.fernandes@empresa.com.br',
      phone: '(11) 98451-2201',
      department: 'Financeiro & Fiscal',
      role: 'Coordenadora Contábil',
      location: 'Matriz - 4º Andar (Home Office Hoje)',
    },
    priority: 'alta',
    urgency: 'alta',
    impact: 'medio',
    status: 'em_atendimento',
    assignedTechnician: TECHNICIANS[0], // Lucas Morais
    assetTag: 'NOTE-FIN-084',
    attachments: [
      {
        id: 'att-1',
        name: 'erro_vpn_print.png',
        sizeKb: 342,
        type: 'image/png',
        uploadedAt: '2026-10-01T08:15:00',
      },
    ],
    timeline: [
      {
        id: 'tm-1',
        type: 'creation',
        author: 'Camila Fernandes',
        authorRole: 'requester',
        content: 'Chamado aberto via Portal de Autoatendimento com prioridade calculada Alta.',
        timestamp: '2026-10-01T08:15:20',
      },
      {
        id: 'tm-2',
        type: 'assignment',
        author: 'Lucas Morais',
        authorRole: 'technician',
        content: 'Chamado assumido por Lucas Morais. Iniciando diagnóstico remoto.',
        timestamp: '2026-10-01T08:22:10',
      },
      {
        id: 'tm-3',
        type: 'internal_note',
        author: 'Lucas Morais',
        authorRole: 'technician',
        content: 'Nota interna: O patch KB5034441 do Windows altera o protocolo TLS padrão. Necessário reinstalar o adaptador virtual WAN Miniport.',
        timestamp: '2026-10-01T08:30:45',
      },
      {
        id: 'tm-4',
        type: 'comment',
        author: 'Lucas Morais',
        authorRole: 'technician',
        content: 'Olá Camila! Identificamos que o adaptador de rede virtual precisava de uma reinicialização de driver. Enviei um script rápido para sua máquina via TeamViewer corporativo.',
        timestamp: '2026-10-01T08:45:00',
      },
    ],
    createdAt: '2026-10-01T08:15:20',
    updatedAt: '2026-10-01T08:45:00',
    slaDeadline: '2026-10-01T16:15:20',
    slaTotalHours: 8,
  },
  {
    id: 'tick-102',
    protocol: 'CH-2026-0841',
    title: 'Falha crítica: Módulo de emissão de NF-e travando no faturamento',
    description: 'Nenhum operador do centro de distribuição consegue emitir notas fiscais. O sistema ERP retorna timeout de comunicação no webservice da SEFAZ ou erro de travamento de sessão no banco.',
    category: 'Sistemas & Softwares',
    subcategory: 'Erro de lançamento no ERP',
    department: 'Sistemas Corporativos',
    requester: {
      name: 'Marcos Vinicius',
      email: 'marcos.vinicius@empresa.com.br',
      phone: '(11) 3214-9988',
      department: 'Operações & Logística',
      role: 'Supervisor de Expedição',
      location: 'CD Itapevi - Bloco Logístico',
    },
    priority: 'critica',
    urgency: 'alta',
    impact: 'alto',
    status: 'em_atendimento',
    assignedTechnician: TECHNICIANS[2], // Rodrigo Valente
    assetTag: 'SRV-ERP-PRD-01',
    attachments: [
      {
        id: 'att-2',
        name: 'log_sefaz_timeout.txt',
        sizeKb: 54,
        type: 'text/plain',
        uploadedAt: '2026-10-01T07:40:10',
      },
    ],
    timeline: [
      {
        id: 'tm-201',
        type: 'creation',
        author: 'Marcos Vinicius',
        authorRole: 'requester',
        content: 'Incidente Crítico reportado. Linha de expedição parada aguardando faturamento de 18 caminhões.',
        timestamp: '2026-10-01T07:40:10',
      },
      {
        id: 'tm-202',
        type: 'assignment',
        author: 'Rodrigo Valente',
        authorRole: 'technician',
        content: 'Atribuído com urgência máxima para Rodrigo Valente (SLA de 2 Horas).',
        timestamp: '2026-10-01T07:45:00',
      },
      {
        id: 'tm-203',
        type: 'internal_note',
        author: 'Rodrigo Valente',
        authorRole: 'technician',
        content: 'Nota interna: O certificado digital A1 da filial venceu às 00:00 de hoje. Atualizando o repositório central com o novo arquivo .pfx renovado pela controladoria.',
        timestamp: '2026-10-01T08:10:00',
      },
    ],
    createdAt: '2026-10-01T07:40:10',
    updatedAt: '2026-10-01T08:10:00',
    slaDeadline: '2026-10-01T09:40:10',
    slaTotalHours: 2,
  },
  {
    id: 'tick-103',
    protocol: 'CH-2026-0839',
    title: 'Monitor 27" Dell apresentando listras horizontais e piscando',
    description: 'O monitor secundário da minha estação de trabalho começou a apresentar faixas pretas e desliga a cada 3 minutos. Já testei a troca do cabo HDMI e o comportamento persiste.',
    category: 'Hardware & Periféricos',
    subcategory: 'Monitor com falha/piscando',
    department: 'TI & Infraestrutura',
    requester: {
      name: 'Juliana Castro',
      email: 'juliana.castro@empresa.com.br',
      phone: '(11) 97722-1133',
      department: 'Comercial & Vendas',
      role: 'Executiva de Contas',
      location: 'Matriz - 2º Andar, Baia 14',
    },
    priority: 'media',
    urgency: 'media',
    impact: 'medio',
    status: 'aguardando_usuario',
    assignedTechnician: TECHNICIANS[1], // Mariana Siqueira
    assetTag: 'MON-COM-019',
    attachments: [],
    timeline: [
      {
        id: 'tm-301',
        type: 'creation',
        author: 'Juliana Castro',
        authorRole: 'requester',
        content: 'Chamado aberto para diagnóstico de periférico.',
        timestamp: '2026-09-30T16:20:00',
      },
      {
        id: 'tm-302',
        type: 'comment',
        author: 'Mariana Siqueira',
        authorRole: 'technician',
        content: 'Olá Juliana! Já separei um monitor reserva no almoxarifado de TI. Você estará no seu posto hoje após as 14h para realizarmos a substituição imediata?',
        timestamp: '2026-10-01T08:50:00',
      },
    ],
    createdAt: '2026-09-30T16:20:00',
    updatedAt: '2026-10-01T08:50:00',
    slaDeadline: '2026-10-01T16:20:00',
    slaTotalHours: 24,
  },
  {
    id: 'tick-104',
    protocol: 'CH-2026-0835',
    title: 'Solicitação de acesso à pasta da Auditoria Externa 2026',
    description: 'Solicito liberação de leitura e gravação no diretório de rede "\\\\srv-files\\Controladoria\\Auditoria_PwC_2026" com autorização prévia em anexo do Diretor Financeiro.',
    category: 'Acessos & Credenciais',
    subcategory: 'Permissão para pasta na rede',
    department: 'Segurança da Informação',
    requester: {
      name: 'Felipe Santana',
      email: 'felipe.santana@empresa.com.br',
      phone: '(11) 3214-5541',
      department: 'Financeiro & Fiscal',
      role: 'Auditor Interno Sênior',
      location: 'Matriz - 4º Andar',
    },
    priority: 'baixa',
    urgency: 'baixa',
    impact: 'baixo',
    status: 'resolvido',
    assignedTechnician: TECHNICIANS[3], // Beatriz Albuquerque
    assetTag: 'USR-FSANTANA',
    attachments: [
      {
        id: 'att-3',
        name: 'aprovacao_diretoria_assinada.pdf',
        sizeKb: 120,
        type: 'application/pdf',
        uploadedAt: '2026-09-30T11:00:00',
      },
    ],
    timeline: [
      {
        id: 'tm-401',
        type: 'creation',
        author: 'Felipe Santana',
        authorRole: 'requester',
        content: 'Solicitação de permissão de pasta criada.',
        timestamp: '2026-09-30T11:00:00',
      },
      {
        id: 'tm-402',
        type: 'assignment',
        author: 'Beatriz Albuquerque',
        authorRole: 'technician',
        content: 'Atribuído para Beatriz Albuquerque para validação de conformidade.',
        timestamp: '2026-09-30T11:30:00',
      },
      {
        id: 'tm-403',
        type: 'resolution',
        author: 'Beatriz Albuquerque',
        authorRole: 'technician',
        content: 'Acesso concedido com sucesso no grupo de segurança "SEC-FS-AUDITORIA-RW". A replicação do Active Directory leva até 15 minutos.',
        timestamp: '2026-09-30T14:15:00',
      },
    ],
    createdAt: '2026-09-30T11:00:00',
    updatedAt: '2026-09-30T14:15:00',
    slaDeadline: '2026-10-02T11:00:00',
    slaTotalHours: 48,
    resolutionSummary: 'Grupo Active Directory atribuído após verificação de assinatura da diretoria.',
    csat: {
      rating: 5,
      comment: 'Atendimento muito ágil e dentro das normas da empresa!',
      submittedAt: '2026-09-30T15:00:00',
    },
  },
  {
    id: 'tick-105',
    protocol: 'CH-2026-0830',
    title: 'Ar condicionado da sala de reuniões 03 pingando água na mesa',
    description: 'A condensadora interna da sala de reuniões da diretoria está com vazamento constante de água, molhando os cabos de rede e a mesa de conferência.',
    category: 'Facilities & Manutenção',
    subcategory: 'Ar condicionado desarmando',
    department: 'Facilities & Predial',
    requester: {
      name: 'Larissa Moura',
      email: 'larissa.moura@empresa.com.br',
      phone: '(11) 98877-6655',
      department: 'Recursos Humanos',
      role: 'Analista de Treinamento',
      location: 'Matriz - 1º Andar, Sala 03',
    },
    priority: 'alta',
    urgency: 'alta',
    impact: 'medio',
    status: 'novo',
    assignedTechnician: null,
    assetTag: 'FAC-AC-003',
    attachments: [],
    timeline: [
      {
        id: 'tm-501',
        type: 'creation',
        author: 'Larissa Moura',
        authorRole: 'requester',
        content: 'Chamado aberto na triagem de Facilities.',
        timestamp: '2026-10-01T08:55:00',
      },
    ],
    createdAt: '2026-10-01T08:55:00',
    updatedAt: '2026-10-01T08:55:00',
    slaDeadline: '2026-10-01T16:55:00',
    slaTotalHours: 8,
  },
  {
    id: 'tick-106',
    protocol: 'CH-2026-0828',
    title: 'Teclado numérico do notebook travando a tecla Enter',
    description: 'Notebook Lenovo ThinkPad com a tecla Enter do bloco numérico emperrada fisicamente após queda de um grampo.',
    category: 'Hardware & Periféricos',
    subcategory: 'Teclado ou Mouse danificado',
    department: 'TI & Infraestrutura',
    requester: {
      name: 'Thiago Barreto',
      email: 'thiago.barreto@empresa.com.br',
      phone: '(11) 99123-4567',
      department: 'Operações & Logística',
      role: 'Assistente Operacional',
      location: 'Matriz - Térreo',
    },
    priority: 'baixa',
    urgency: 'baixa',
    impact: 'baixo',
    status: 'fechado',
    assignedTechnician: TECHNICIANS[1],
    assetTag: 'NOTE-LOG-014',
    attachments: [],
    timeline: [
      {
        id: 'tm-601',
        type: 'creation',
        author: 'Thiago Barreto',
        authorRole: 'requester',
        content: 'Chamado aberto para limpeza técnica de teclado.',
        timestamp: '2026-09-29T10:00:00',
      },
      {
        id: 'tm-602',
        type: 'resolution',
        author: 'Mariana Siqueira',
        authorRole: 'technician',
        content: 'Limpeza e desobstrução mecânica realizadas no laboratório.',
        timestamp: '2026-09-29T11:45:00',
      },
    ],
    createdAt: '2026-09-29T10:00:00',
    updatedAt: '2026-09-29T11:45:00',
    slaDeadline: '2026-10-01T10:00:00',
    slaTotalHours: 48,
    resolutionSummary: 'Limpeza física com ar comprimido e teste das teclas.',
    csat: {
      rating: 5,
      comment: 'Muito rápido!',
      submittedAt: '2026-09-29T12:00:00',
    },
  },
];

export const CANNED_RESPONSES: CannedResponse[] = [
  {
    id: 'cr-1',
    title: 'Solicitar mais evidências / Prints',
    content: 'Olá! Para podermos dar seguimento com precisão ao seu chamado, você poderia nos enviar um print da tela inteira exibindo a mensagem de erro e o horário aproximado do ocorrido?',
  },
  {
    id: 'cr-2',
    title: 'Agendamento de visita presencial',
    content: 'Olá! Analisamos a sua solicitação e será necessária uma intervenção técnica presencial em sua estação de trabalho. Você estará disponível no local no período da tarde entre 14:00 e 16:00?',
  },
  {
    id: 'cr-3',
    title: 'Senha redefinida temporariamente',
    content: 'Sua senha do Active Directory foi redefinida com sucesso. Foi enviado um SMS com a senha temporária para o seu celular corporativo cadastrado. No primeiro acesso, será solicitada a criação da sua nova senha pessoal.',
  },
  {
    id: 'cr-4',
    title: 'Aguardando validação do solicitante',
    content: 'Realizamos os ajustes necessários em seu equipamento/sistema. Por gentileza, realize um novo teste e confirme se a ocorrência foi solucionada para que possamos concluir este chamado.',
  },
];

export const KNOWLEDGE_ARTICLES: KnowledgeArticle[] = [
  {
    id: 'kb-1',
    title: 'Como conectar na VPN Corporativa (Passo a Passo)',
    category: 'Redes & Conectividade',
    summary: 'Guia completo para login seguro na rede interna da empresa via FortiClient e autenticação em dois fatores (MFA).',
    content: `1. Abra o aplicativo FortiClient VPN na barra de tarefas ao lado do relógio.
2. Certifique-se de que a conexão selecionada seja "VPN-CORPORATIVA-SSL".
3. Digite seu usuário de rede (exemplo: joao.silva) e sua senha usual de computador.
4. Clique em "Conectar". Uma notificação do Microsoft Authenticator surgirá no seu celular.
5. Aprove a notificação no celular digitando o número de dois dígitos exibido na tela do computador.
6. Quando o status mudar para "Conectado (100%)", você terá acesso aos servidores e ao ERP.`,
    tags: ['vpn', 'forticlient', 'home office', 'redes', 'mfa'],
    views: 1420,
    helpfulCount: 388,
    updatedAt: '2026-09-15',
  },
  {
    id: 'kb-2',
    title: 'Como redefinir sua senha de rede de forma autônoma',
    category: 'Acessos & Credenciais',
    summary: 'Use o portal de autoatendimento Microsoft SSPR para trocar ou desbloquear sua senha sem precisar abrir chamado.',
    content: `Se você esqueceu sua senha ou a conta foi bloqueada por tentativas incorretas:
1. Acesse https://passwordreset.microsoftonline.com em qualquer navegador (pode ser pelo celular).
2. Digite seu e-mail corporativo completo.
3. Valide sua identidade via código SMS ou aplicativo Authenticator.
4. Defina uma nova senha que contenha no mínimo 10 caracteres, incluindo letras maiúsculas, números e símbolo.
5. Aguarde 2 minutos para replicação e faça o login no seu Windows.`,
    tags: ['senha', 'desbloqueio', 'active directory', 'sspr', 'login'],
    views: 2840,
    helpfulCount: 912,
    updatedAt: '2026-09-20',
  },
  {
    id: 'kb-3',
    title: 'Configuração e mapeamento de impressoras de rede',
    category: 'Hardware & Periféricos',
    summary: 'Procedimento para adicionar as impressoras dos andares 1º, 2º e 4º da Matriz.',
    content: `1. Pressione as teclas Windows + R no teclado para abrir o comando Executar.
2. Digite: \\\\srv-print-01 e pressione Enter.
3. Localize o modelo correspondente ao seu andar (ex: IMP-ANDAR-02-COLOR).
4. Dê duplo clique no ícone da impressora.
5. O Windows baixará os drivers automaticamente em cerca de 30 segundos.
6. Defina como impressora padrão caso utilize diariamente.`,
    tags: ['impressora', 'toner', 'papel', 'impressão', 'rede'],
    views: 940,
    helpfulCount: 215,
    updatedAt: '2026-08-10',
  },
  {
    id: 'kb-4',
    title: 'Limpeza de cache e resolução de travamentos no ERP Protheus',
    category: 'Sistemas & Softwares',
    summary: 'Como resolver mensagens de congelamento ou inconsistência de tela no SmartClient.',
    content: `Ao se deparar com erros de "Thread Error" ou tela preta ao carregar rotinas financeiras:
1. Feche todas as instâncias do Protheus abertas.
2. Pressione Windows + R e digite: %temp%
3. Selecione e exclua as pastas temporárias iniciadas por "totvs" ou "smartclient".
4. Reinicie o aplicativo Protheus executando como Administrador.
5. Caso o erro persista, abra um chamado com anexo do arquivo console.log.`,
    tags: ['erp', 'protheus', 'totvs', 'smartclient', 'erro'],
    views: 1105,
    helpfulCount: 310,
    updatedAt: '2026-09-01',
  },
];
